export const ERROR_CODES = {
  UNKNOWN: 'UNKNOWN_ERROR',

  NETWORK: 'NETWORK_ERROR',

  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_CONFIRMED: 'AUTH_EMAIL_NOT_CONFIRMED',
  AUTH_USER_ALREADY_EXISTS: 'AUTH_USER_ALREADY_EXISTS',
  AUTH_INVALID_OTP: 'AUTH_INVALID_OTP',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',

  VALIDATION: 'VALIDATION_ERROR',

  DATABASE: 'DATABASE_ERROR',
  API: 'API_ERROR',
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];